### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by lecorguille**
@melpetera 
The planemo test pass on our cluster. But it seem that it is too long for travis.

I will try to figure out which step is time consuming and if I can, I should try to optimize a little.

But I guess that this kind of [loops](https://github.com/workflow4metabolomics/correlation_analysis/blob/lecorguille_refactoring/correlation_analysis.r#L102) aren't so much R friendly (as they are in Python for instance)

```R
    for(pcgroup in pcgroups){
        #Select a subset data frame for each pcgroup
        subset_data=new_dataframe[new_dataframe$pcgroup==pcgroup,]
        #Stores the metabolites names for each pcgroup into a matrix one dimension.
        pc_group_elements=t(as.matrix(subset_data[3]))
        #uses the matrix "pc_group_elements" containing the metabolites to have the correlation data frame "subset_data2" by pcgroup
        subset_data2=subset_data[names(subset_data) %in% c(names(output_tsv)[3],pc_group_elements) ]

        #print("2")
        #We keep the first metabolites for each pcgroup that correspond to the metabolites with the highest amount of signal
        first_metabolite=pc_group_elements[1]
        #Remove the first metabolite from the pc_group_elements matrix
        pc_group_elements=pc_group_elements[,c(1:length(pc_group_elements))]
        #print (pc_group_elements)
        for(metabolite in pc_group_elements){
            metabolite_dataframe=subset_data2[subset_data2[,first_column]==metabolite,]
            #retrives metabolite index from the vector object "pc_group_elements" 
            index_metabolite=as.numeric(which(pc_group_elements==metabolite, arr.ind=TRUE))
            for (f in 2:index_metabolite-1 ) {           
                if (metabolite!=first_metabolite) {
                    value_intensity=t(data.matrix(metabolite_dataframe[,pc_group_elements[f]]))
                    value_intensity=value_intensity[1:1]
                    #If one value is >0.75, it means that the metabolite est correlated with at least one previous metabolite in the table, so the boolean variable is set to true.
                    if (value_intensity>param_correlation){
                        new_dataframe$suppress[new_dataframe[,first_column] ==metabolite ] <- "DEL"
                    }
                }
            }        
        }   
    }
```

### CODE REVIEW

**Comment by melpetera** [comment]
I am not confortable with code optimisation, but I can try to test the code with your datasets on my computer to find what step is taking so much time, at least.

**Comment by melpetera** [comment]
I tested it on my computer. It is not directly linked to code optimisation: your test datasets contain 8157 ions, meaning that you construct a correlation matrix 8157x8157 (1.12 Go), filter it (780 Mo) and create the sif table (264 Mo) (output files = 2,14 Go). It is a little to much for test datasets, isn't it? It took  1 hour to process it on my computer, so no wonder travis did not like it. 

More details about execution time:
- Before the big loop: 1 min
- Big loop time: 14 min (6245 iterations)
- Processing after the loop and before de tables export: 20 min
- File export: all that remain (it is long because of the tables dimensions)

This is on my computer and Windows, so even if I made the test when I was away to let the computer alone, this timings are still just illustrative.

**Comment by lecorguille** [comment]
OK!
Indeed, it seems that I need to reduce the test-data.
Meanwhile, can a dataset of 8157 ions be considered as a classic case?

**Comment by melpetera** [comment]
I would not call it a classic case. It can happen to have that many ions depending on your analysis and choices of extraction parameters. However usually when arriving at this correlation analysis step, even if this tool can be used to filter, it will already be some reduced dataset. 

I would say that a "classic" size would be from 1200 to 1700 ions. It can also be 700 or 2500 but if I had to choose a number I would say 1400. But this is only my opinion, based on my own experience in MS datasets. 

Anyway, for a test dataset, 1000 should be way enough (even less if you want to be fast).

**Comment by melpetera** [comment]
All good for me 👍

**Pull request merged**
